import React from 'react';
import { X, FileText, Download, ShieldCheck } from 'lucide-react';
import type { ReportHistoryRecord } from './ReportHistoryTable';

interface ReportDrawerProps {
  open: boolean;
  onClose: () => void;
  record: ReportHistoryRecord | null;
  onDownload: (rec: ReportHistoryRecord) => void;
}

export const ReportDrawer: React.FC<ReportDrawerProps> = ({
  open,
  onClose,
  record,
  onDownload,
}) => {
  if (!open || !record) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      <div className="absolute inset-0 bg-background/80 backdrop-blur-xs" onClick={onClose} />

      <div className="fixed inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-lg bg-card border-l border-border shadow-2xl flex flex-col">
          {/* Drawer Header */}
          <div className="p-5 border-b border-border flex items-center justify-between bg-muted/30">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-primary/10 text-primary">
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <h2 className="text-base font-black text-foreground">Report Audit Inspector</h2>
                <p className="text-xs text-muted-foreground mt-0.5 font-mono">{record.id}</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Drawer Body */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6 text-xs">
            <div className="p-4 rounded-2xl border border-primary/20 bg-primary/5 space-y-2">
              <div className="flex items-center justify-between">
                <span className="font-bold text-foreground">System Audit Verification</span>
                <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-600 font-mono text-[10px] font-bold">
                  {record.status}
                </span>
              </div>
              <p className="text-muted-foreground text-xs leading-relaxed">
                Report generated automatically from verified production server database logs. Hash signature matched.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="text-xs font-bold text-foreground uppercase tracking-wider flex items-center gap-1.5">
                <ShieldCheck className="h-3.5 w-3.5 text-primary" />
                Report Metadata
              </h4>

              <div className="space-y-2 font-mono">
                <div className="flex justify-between p-3 rounded-xl border border-border bg-card">
                  <span className="text-muted-foreground">Report Title:</span>
                  <span className="font-bold text-foreground font-sans truncate max-w-[200px]">
                    {record.reportName}
                  </span>
                </div>
                <div className="flex justify-between p-3 rounded-xl border border-border bg-card">
                  <span className="text-muted-foreground">Category:</span>
                  <span className="font-bold text-emerald-600">{record.category}</span>
                </div>
                <div className="flex justify-between p-3 rounded-xl border border-border bg-card">
                  <span className="text-muted-foreground">Format:</span>
                  <span className="font-bold text-foreground">{record.format}</span>
                </div>
                <div className="flex justify-between p-3 rounded-xl border border-border bg-card">
                  <span className="text-muted-foreground">Generated At:</span>
                  <span className="font-bold text-foreground">{record.generatedAt}</span>
                </div>
                <div className="flex justify-between p-3 rounded-xl border border-border bg-card">
                  <span className="text-muted-foreground">Generated By:</span>
                  <span className="font-bold text-foreground">{record.generatedBy}</span>
                </div>
                <div className="flex justify-between p-3 rounded-xl border border-border bg-card">
                  <span className="text-muted-foreground">File Size:</span>
                  <span className="font-bold text-blue-600">{record.fileSize}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Drawer Footer */}
          <div className="p-4 border-t border-border bg-muted/20 flex items-center gap-2">
            <button
              onClick={onClose}
              className="flex-1 py-2.5 rounded-xl border border-input bg-card text-foreground font-bold text-xs hover:bg-muted transition-colors"
            >
              Close
            </button>
            <button
              onClick={() => onDownload(record)}
              className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-primary text-white font-bold text-xs hover:bg-primary/90 transition-colors shadow-md"
            >
              <Download className="h-4 w-4" />
              Download File
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportDrawer;
